# Generated by Django 6.0.2 on 2026-03-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remains', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.day')),
            ],
        ),
        migrations.CreateModel(
            name='Сonsumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('count', models.DecimalField(decimal_places=2, max_digits=30)),
                ('prise', models.DecimalField(decimal_places=2, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.day')),
            ],
        ),
    ]
